spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/account_service
    username: acc_user
    password: 8a0c0d42d07cd908b58543cc69ee7bf4
    sql-script-encoding: UTF-8
    initialization-mode: always
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: auth_user
    password: 713993829bf5be2523f081280b65c2b8
    virtual-host: /authorization
  mail:
    host: 192.168.99.100
    port: 1025
    username:
    password: 
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  zipkin:
    base-url: http://app-blesk-tracking-server:59fe09743cb9ef59276464f81734a003@192.168.99.100:9411/
eureka:
  client:
    service-url:
      defaultZone: http://app-blesk-naming-server:b1477e9ba7723b8f47e9727a39a51edf@192.168.99.100:8761/eureka
security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwySCnVbkvES/mMHJllnN
                   M5lQ9m26uXbbJzohBhCQyRe/wvuC1UqXDNd45VsgGWk2zZ9/36EH0DZLrrTMR487
                   Xqa+/OWm1ZDlNRKJDBcHv/WWcx1XULS3uC3hvcz/7kFTQTj80vvfhtUOfl7mXMh7
                   hznvKqB2oe067ZDzigqlDPjBCVpmGC77aHcw7HF4NVnsDki8oHUs9uEB2IHDrcpY
                   cSUivEwI2cN1mWDSQtoH3WRxHe39nIE748tLatkjvmKLzArugbuWh3his10DAVfU
                   Lg3kLRDtIBadvxxRZPqjyeSjFL0ti8yO4Dahyg4iDrBhY2Xc9kUeZssRxETbxmu0
                   BQIDAQAB
                   -----END PUBLIC KEY-----
blesk:
  javamailer:
    from: no-reply@blesk.sk
    url:
      forget-password: http://www.blesk.sk/forgetpassword/account/%s/token/%s
      account-activation: http://www.blesk.sk/signup/account/%s/token/%s