spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/account_service
    username: acc_user
    password: 8a0c0d42d07cd908b58543cc69ee7bf4
    sql-script-encoding: UTF-8
    initialization-mode: always
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: auth_user
    password: 3bc7c46858e6b89143ff90f1fde9d1d6
    virtual-host: /authorization
  mail:
    host: 192.168.99.100
    username: ""
    password: ""
    port: 1025
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
blesk:
  rabbitmq:
    authorization-exchange: blesk.authorizationExchange
    dead-letter-exchange: blesk.deadLetterExchange
    authorization-queue: blesk.authorizationQueue
    dead-letter-queue: blesk.deadLetterQueue
    authorization-routing-key: blesk.authorizationRoutingKey
    dead-letter-routing-key: blesk.deadLetterRoutingKey
    dead-letter-routing-key-argument: x-dead-letter-routing-key
    dead-letter-exchange-argument: x-dead-letter-exchange