spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/account_service
    username: acc_user
    password: 8a0c0d42d07cd908b58543cc69ee7bf4
    sql-script-encoding: UTF-8
    initialization-mode: always
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false