spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/authorization_server
    username: auth_user
    password: 369cb8aedcca0644afa0b1f366c87dbf
    sql-script-encoding: UTF-8
    initialization-mode: always
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: app_user
    password: a880694a8723cc8781afca52be082aa6
    virtual-host: /messaging
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  zipkin:
    base-url: http://192.168.99.100:9411/
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
config:
    oauth2:
        client-id: 8de4dc56-6e96-11ea-bc55-0242ac130003
        client-secret: 04ed73c86f2d48e9789fa2d2bae6acf78bcd9b431d676e5f6d9c9c9a28de29a3
        access-token-validity: 3600
        refresh-token-validity: 18000
        max-attempts: 3
        private-key: -----BEGIN RSA PRIVATE KEY-----
                     MIIEowIBAAKCAQEAwySCnVbkvES/mMHJllnNM5lQ9m26uXbbJzohBhCQyRe/wvuC
                     1UqXDNd45VsgGWk2zZ9/36EH0DZLrrTMR487Xqa+/OWm1ZDlNRKJDBcHv/WWcx1X
                     ULS3uC3hvcz/7kFTQTj80vvfhtUOfl7mXMh7hznvKqB2oe067ZDzigqlDPjBCVpm
                     GC77aHcw7HF4NVnsDki8oHUs9uEB2IHDrcpYcSUivEwI2cN1mWDSQtoH3WRxHe39
                     nIE748tLatkjvmKLzArugbuWh3his10DAVfULg3kLRDtIBadvxxRZPqjyeSjFL0t
                     i8yO4Dahyg4iDrBhY2Xc9kUeZssRxETbxmu0BQIDAQABAoIBAG4CnSe6HsUMNL8X
                     MF/0TDx0iDIEdimsGawplwhmOllDbDWtuHopzLHOnzcdgiERMXYGHv6hN1hn446g
                     GjGVS7D2a+ECTmVDhBPBWUVZjmLnPmOy/NBgsNnB8+seMIHOjfLM/6qpl7/ZSIxx
                     T4iq9Qis3mm3gGmU5Y2cE8+UZKvEbC9dlUrHYUNo76j0KToqoNwFymNPUzUSyA+d
                     iQmQIQNy31e+G5SNUYeorGXR8rVrgk67YAWzmTJUzqO+9e9fS9BqzSYFDCCwaNdU
                     YSfwIav9CGCsVN7u2jZM5yyMPZuHgZPyxRm55vgS6iqbFxmoFkdjVmhvhmAHMiWY
                     5c0KVJkCgYEA6rpCH1hqTQKdoaznkv0Kc2ImnKbelU9PDj2r9upsTGOM87tSFlCv
                     McQjdAwVXlcTh4D/a+SYOcHYi2hURpAomjOuzLCeMYWkyBx9ZPw//UAGTaq8TKEt
                     iotOWT0m1tC5OvAeH43E/FPVmtLis8/cZw86poc4IE8mt3ZqjbuLnRMCgYEA1NPe
                     25wicdGb15oWpoYYxDjX9CXsFEcB2PsRfvFI7/AiDU+DiPJBcRKhKNfWjJ8CdsUC
                     +hcBwKroTuWAw6NKbTYIXPUWyIKFztYHtI0IJB5OZmx1J6whmBfb5n2HmBew73iH
                     i0sg/0dk9hNq44Vik+hQbEYg3AEuWaIocNcrhYcCgYEApKZgiYJIlpp2HhmeGyI6
                     eXNo6Eu5KH0IVFH4VWxc6TyPe8xzKUoRilQuFlH/jzx/a3aWNIWWLjWGg0t8ij7G
                     7FvCirx9SvmW+/PYFcVH0YpeoY5ZJVuOCXfsTnaxzs98jxYt2y5j9ieMV10EPuNY
                     lEY/et6xBSDgZKLA3Yinx1cCgYAsKyBIEVowpuCh2Q+0VYYUSvu+ZpRdDPN8NXbH
                     EoohiYN3obXZmPUt40Dg+hJDsshPH8njXxz1AEMgBI85iszqZ1lK+W5WBIiCiXal
                     6NL0s/lvVjjmF9oM936ikhCu5tPIjwoKRXg+onF4hEUdnNP9gCwYnGE7Z19YKMgd
                     yvn0RwKBgDK8RP58qyEHRB52La33PBMubD3JvIh0Sx1RVU9c0WhotaLiZs6KWrpA
                     4Tgzxw/bImb526+MDNQhYDu0m5AxWxbnrXEM4Jp+3dB7iJVaaoxNRhKT/bUkrt/5
                     LK0ojxkkvsvpYP4iLhqHzj10k4TbK9mz582SmoN07ekT1vtqr2Em
                     -----END RSA PRIVATE KEY-----
        public-key: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwySCnVbkvES/mMHJllnN
                   M5lQ9m26uXbbJzohBhCQyRe/wvuC1UqXDNd45VsgGWk2zZ9/36EH0DZLrrTMR487
                   Xqa+/OWm1ZDlNRKJDBcHv/WWcx1XULS3uC3hvcz/7kFTQTj80vvfhtUOfl7mXMh7
                   hznvKqB2oe067ZDzigqlDPjBCVpmGC77aHcw7HF4NVnsDki8oHUs9uEB2IHDrcpY
                   cSUivEwI2cN1mWDSQtoH3WRxHe39nIE748tLatkjvmKLzArugbuWh3his10DAVfU
                   Lg3kLRDtIBadvxxRZPqjyeSjFL0ti8yO4Dahyg4iDrBhY2Xc9kUeZssRxETbxmu0
                   BQIDAQAB
                   -----END PUBLIC KEY-----