spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: track_user
    password: e19e0344779bf3cfa03f1cc2e98bd424
    virtual-host: /inspection
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  zipkin:
    base-url: http://app-blesk-tracking-server:59fe09743cb9ef59276464f81734a003@192.168.99.100:9411/
eureka:
  client:
    service-url:
      defaultZone: http://app-blesk-naming-server:b1477e9ba7723b8f47e9727a39a51edf@192.168.99.100:8761/eureka
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    authorization-server:
      path: /authorization-server/**
      url: http://192.168.99.100:9090
    account-service:
      path: /account-service/**
      url: http://192.168.99.100:7000
    user-service:
      path: /user-service/**
      url: http://192.168.99.100:7200
security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwySCnVbkvES/mMHJllnN
                   M5lQ9m26uXbbJzohBhCQyRe/wvuC1UqXDNd45VsgGWk2zZ9/36EH0DZLrrTMR487
                   Xqa+/OWm1ZDlNRKJDBcHv/WWcx1XULS3uC3hvcz/7kFTQTj80vvfhtUOfl7mXMh7
                   hznvKqB2oe067ZDzigqlDPjBCVpmGC77aHcw7HF4NVnsDki8oHUs9uEB2IHDrcpY
                   cSUivEwI2cN1mWDSQtoH3WRxHe39nIE748tLatkjvmKLzArugbuWh3his10DAVfU
                   Lg3kLRDtIBadvxxRZPqjyeSjFL0ti8yO4Dahyg4iDrBhY2Xc9kUeZssRxETbxmu0
                   BQIDAQAB
                   -----END PUBLIC KEY-----
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000
server:
  error:
    whitelabel:
      enabled: false