spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: track_user
    password: e19e0344779bf3cfa03f1cc2e98bd424
    virtual-host: /inspection
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  zipkin:
    base-url: http://app-blesk-tracking-server:59fe09743cb9ef59276464f81734a003@tracking-server:9411/
eureka:
  client:
    service-url:
      defaultZone: http://app-blesk-naming-server:b1477e9ba7723b8f47e9727a39a51edf@naming-server:8761/eureka
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    authorization-server:
      path: /authorization-server/**
      url: http://authorization-server:9090
    account-service:
      path: /account-service/**
      url: http://account-service:7000
    user-service:
      path: /user-service/**
      url: http://user-service:7200
    messaging-service:
      path: /messaging-service/**
      url: http://messaging-service:7400
    place-service:
      path: /place-service/**
      url: http://place-service:5000
    warehouse-service:
      path: /warehouse-service/**
      url: http://warehouse-service:5400
    vehicle-service:
      path: /vehicle-service/**
      url: http://vehicle-service:5200
    shipment-service:
      path: /shipment-service/**
      url: http://shipment-service:5600
    parcel-service:
      path: /parcel-service/**
      url: http://parcel-service:5800
security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwySCnVbkvES/mMHJllnN
                   M5lQ9m26uXbbJzohBhCQyRe/wvuC1UqXDNd45VsgGWk2zZ9/36EH0DZLrrTMR487
                   Xqa+/OWm1ZDlNRKJDBcHv/WWcx1XULS3uC3hvcz/7kFTQTj80vvfhtUOfl7mXMh7
                   hznvKqB2oe067ZDzigqlDPjBCVpmGC77aHcw7HF4NVnsDki8oHUs9uEB2IHDrcpY
                   cSUivEwI2cN1mWDSQtoH3WRxHe39nIE748tLatkjvmKLzArugbuWh3his10DAVfU
                   Lg3kLRDtIBadvxxRZPqjyeSjFL0ti8yO4Dahyg4iDrBhY2Xc9kUeZssRxETbxmu0
                   BQIDAQAB
                   -----END PUBLIC KEY-----
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000
server:
  error:
    whitelabel:
      enabled: false
blesk:
  cors:
    allowed:
      origins: "http://pwa-react:4200/, http://web-vue:4300/, http://admin-angular:4400/"
      methods: "HEAD, GET, PUT, POST, DELETE, PATCH"