spring:
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/user_service
    username: usr_user
    password: 260a87a10ddd9dc9e7f04f05d746a532
    sql-script-encoding: UTF-8
    initialization-mode: always
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: track_user
    password: e19e0344779bf3cfa03f1cc2e98bd424
    virtual-host: /inspection
  mail:
    host: 192.168.99.100
    port: 1025
    username:
    password: 
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  zipkin:
    base-url: http://app-blesk-tracking-server:59fe09743cb9ef59276464f81734a003@192.168.99.100:9411/
redis:
  database:
    host: 192.168.99.100
    port: 6379
    password: bae775e59991582c5ac867120f39bf80
stripe:
  key:
    public: pk_test_51Gs4j4KeDkPznmYygfxMZvAaqll3yvylXlEMwihtyJySScYQEvQkVCuPAIYQcY5EA2AnBRLXB8KOfa9HOiPPyc3a008MI5W1vi
    secret: sk_test_51Gs4j4KeDkPznmYy6DHxUvPv2GkERMBYyEXA0WQAqagpvKgyDBqbjkySfbWaWPfnOfRSyzLsaflXj42YyWEMjPy6002yrUaovU
eureka:
  client:
    service-url:
      defaultZone: http://app-blesk-naming-server:b1477e9ba7723b8f47e9727a39a51edf@192.168.99.100:8761/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000
security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwySCnVbkvES/mMHJllnN
                   M5lQ9m26uXbbJzohBhCQyRe/wvuC1UqXDNd45VsgGWk2zZ9/36EH0DZLrrTMR487
                   Xqa+/OWm1ZDlNRKJDBcHv/WWcx1XULS3uC3hvcz/7kFTQTj80vvfhtUOfl7mXMh7
                   hznvKqB2oe067ZDzigqlDPjBCVpmGC77aHcw7HF4NVnsDki8oHUs9uEB2IHDrcpY
                   cSUivEwI2cN1mWDSQtoH3WRxHe39nIE748tLatkjvmKLzArugbuWh3his10DAVfU
                   Lg3kLRDtIBadvxxRZPqjyeSjFL0ti8yO4Dahyg4iDrBhY2Xc9kUeZssRxETbxmu0
                   BQIDAQAB
                   -----END PUBLIC KEY-----
blesk:
  server-key: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbl9pZCI6MSwiYWNjb3VudF9pZCI6MSwidXNlcl9uYW1lIjoic3lzdGVtIiwic2NvcGUiOlsidHJ1c3QiXSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9TWVNURU0iXSwianRpIjoiZWM3ZmE5ZGItZmY0MS00NmU4LWI4OTctMDI1YWE1YWFlMWQ2IiwiY2xpZW50X2lkIjoiOGRlNGRjNTYtNmU5Ni0xMWVhLWJjNTUtMDI0MmFjMTMwMDAzIiwiYWN0aXZhdGVkIjp0cnVlfQ.KzxBtlmKOliwE8tdbeBgXgWb3vlcRp4-x4vmVA-2wI4GfWtK1d-Ax4QQDImOqhnRNh81H9H0SxPYaurSo_RJUpt35iXUSmIp5rizGXAj3xge9tf5o1jeZcVmuipzoZzF46cdnakmjaOk3fwerX50p_egO62ew8DdUgcpNpz7cyZH7-0ebAziYNibaka0s5NwksEhrFmK1BAxu-8_couQI3R5E_veygCnA92i6gkO-4BQS342vnHgpI31QT5lm9BG_KM6ADqDFYwD_JCRCVeUzQymP2YL3jOlDsdJ_p5vzNjGDrJIfSwMPDL-sIGZ9QbyXL7ffgbIiga1XI3qJ6UcGA'
  javamailer:
    from: no-reply@blesk.sk